### ISSUE TITLE
Github contributions image referenced as HTTP inside HTTPS site

### ISSUE THREAD

**Issue by dmsnell** [meiqimichelle/mhertzfeld#35]
The Github contribution image is being requested as a non-secure HTTP request even though the site is served as HTTP. This results in a mixed-content warning in the browser console.

<img width="468" alt="screen shot 2017-01-02 at 11 25 23 pm" src="https://cloud.githubusercontent.com/assets/5431237/21601076/d8d68cb8-d142-11e6-9a04-5e4a9ac2d001.png">

It appears already as HTTPS [in the source](https://github.com/meiqimichelle/mhertzfeld/blame/c57ed7c2ac157328e0ca0b79613bd64aa59a5cba/_posts/2015-01-07-pif-reflections.md#L57) and was modified in 9823173

**Comment by dmsnell** [comment]
Maybe this can be resolved by using `{{ site.baseurl }}` instead of the actual `https://meiqi…` URL in the post source files.

**Comment by meiqimichelle** [comment]
I believe this specific image problem is resolved with 9a0c322cca071730718e6358cd427769ac3254df . Turned out, there were plenty more where that came from. I believe all are now resolved with 3c8236c8490d49f3adb4ddc7b7a5ec25aa5540dc . 

I think in an earlier iteration of the site, I was having issues with relative paths to images in .md post files. That has since been resolved, but I hadn't bothered to go back through the older posts and update all the images to absolute paths because I thought it wasn't causing any harm. In reality, it was causing the issue you raised here @dmsnell (thank you!), as well as borking my `@2x` image file delivery for clear display on retina/hi-pixel-density screens. Fixing this also helped fix #1 .

Closing. Please re-open if needed.
